# fly.toml app configuration file generated for lively-resonance-5671 on 2023-08-09T20:30:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-resonance-5671"
primary_region = "yul"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
