default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  pool: 5
  port: 5432
  username: postgres
  password: 1234

test:
  <<: *default
  database: myapp_test
  pool: 5
  port: 5432
  username: postgres
  password: 1234

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: novo_production
  username: novo
  password: <%= ENV["NOVO_DATABASE_PASSWORD"] %>
